export function handleException(status) {
	console.log("에러가 발생했습니다.", status);
}
